# Generated by Django 3.2 on 2022-01-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("gpu", models.CharField(max_length=20)),
                ("cpu", models.CharField(max_length=20)),
                ("ram", models.CharField(max_length=20)),
            ],
        ),
    ]
