# Generated by Django 4.0.1 on 2022-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_blog_delete_laptop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="read_more",
            field=models.URLField(blank=True),
        ),
    ]
