# Generated by Django 4.0.2 on 2022-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_alter_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
