# Generated by Django 4.0.2 on 2022-02-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_blog_category_alter_blog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="desc",
            field=models.CharField(max_length=200),
        ),
    ]
