# Generated by Django 4.0.2 on 2022-02-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_alter_blog_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="read_more",
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="blog",
            name="thumbnail",
            field=models.URLField(max_length=400),
        ),
    ]
