# Generated by Django 4.0.3 on 2022-03-20 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0009_blog_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_content",
            field=ckeditor.fields.RichTextField(default=" "),
        ),
    ]
