# Generated by Django 4.0.3 on 2022-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0011_alter_blog_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="approve_status",
            field=models.BooleanField(default=False),
        ),
    ]
