# Generated by Django 4.0.3 on 2022-03-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_blog_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(blank=True, default='unknown user', max_length=100, null=True),
        ),
    ]
