# Generated by Django 4.0.3 on 2022-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(default="default.jpg", upload_to="pictures/"),
        ),
    ]
